from stocks.research.continuous.contracts_v2_39 import EntityV239,EvidenceRecordV239
from stocks.research.continuous.health_v2_39_1 import assess_entity_hardened
from stocks.research.continuous.store_v2_39 import ResearchStoreV239,utc_now
POL={'stale_evidence_hours':999,'promotion_evidence_fresh_hours':999,'psi_watch':.1,'psi_quarantine':.25,'js_watch':.08,'js_quarantine':.2,'decay_watch':.35,'decay_quarantine':.7,'disagreement_watch':.45,'disagreement_quarantine':.75,'minimum_shadow_trades_for_promotion_review':30,'minimum_independent_evidence_classes':2,'minimum_independent_evidence_sources':2,'minimum_oos_observations':60,'minimum_posterior_net_edge_bps':0,'minimum_cost_stress_multiplier':2.0,'require_cost_robustness_for_champion_review':True,'require_fresh_outcome_evidence':True,'minimum_quality_score_for_champion_review':.72}
B={'prior_mean_bps':0,'prior_strength':20};W={'statistical_validation':.15,'oos_robustness':.15,'cost_robustness':.15,'shadow_evidence':.15,'cross_engine':.10,'generalization':.10,'calibration':.05,'evidence_breadth':.10,'freshness':.05}
def test_registry_only_quality_is_not_perfect(tmp_path):
 s=ResearchStoreV239(tmp_path/'r.db');s.upsert_entity(EntityV239('S','STRATEGY',role='CHALLENGER'));s.add_evidence(EvidenceRecordV239('S','REGISTRY_SNAPSHOT',utc_now(),{'validation_status':'VALIDATED','cross_engine_validated':True,'dynamic_universe_generalized':True},'registry','r',1));a=assess_entity_hardened(s,'S',policy=POL,bayesian=B,quality_weights=W);assert 0<a.score<.5
def test_more_real_evidence_increases_quality(tmp_path):
 s=ResearchStoreV239(tmp_path/'r.db');s.upsert_entity(EntityV239('S','STRATEGY',role='CHALLENGER'));s.add_evidence(EvidenceRecordV239('S','REGISTRY_SNAPSHOT',utc_now(),{'validation_status':'VALIDATED','cross_engine_validated':True,'dynamic_universe_generalized':True},'registry','r',1));a0=assess_entity_hardened(s,'S',policy=POL,bayesian=B,quality_weights=W);s.add_evidence(EvidenceRecordV239('S','OOS_VALIDATION',utc_now(),{'net_edge_bps':20,'quality_score':.9,'observations':100},'v2.33','o',100));s.add_evidence(EvidenceRecordV239('S','COST_STRESS',utc_now(),{'stress_multiplier':3,'net_edge_bps':8},'v2.36','c',100));a1=assess_entity_hardened(s,'S',policy=POL,bayesian=B,quality_weights=W);assert a1.score>a0.score and a1.score<1
